#!/bin/bash

declare -A tasks=(
    [2]="print_alphabet"
    [3]="print_alphabt"
    [4]="print_hexa"
    [5]="print_comb"
    [6]="print_comb2"
    [7]="islower"
    [8]="print_last_digit"
    [9]="add"
    [10]="print_line"
    [11]="print_diagonal"
    [12]="fizzbuzz"
)

for i in "${!tasks[@]}"
do
    mkdir -p $i-${tasks[$i]}
    cd $i-${tasks[$i]}
    dotnet new console
    mv Program.cs $i-${tasks[$i]}.cs
    cat > $i-${tasks[$i]}.csproj << EOL
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <RootNamespace>_${i}_${tasks[$i]}</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
EOL
    cd ..
done
